### ISSUE TITLE
When sending a message to a user, the conversation does not appear on the receiver until refreshing

### ISSUE THREAD

**Issue by marcosnc08** [cometchat/cometchat-uikit-react#136]
### Describe the problem

Hey guys,

When sending a message to a user, the conversation does not appear on the receiver until I update the page.

### What was the expected behavior?

The new conversation should appear

### Reproduction

1. Run your react sample app with UI Kit v4

2. Use the API to send a message to the user

3. The message does not appear until updating the page

Video of the bug: https://youtu.be/eIzsP1qV1D0

### Environment

React UI Kit v4
React Sample with UI Kit v4

**Comment by ketanyekale** [comment]
This has been fixed. Please try the latest version of the UI Kit v4.x.
